package worker

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/google/generative-ai-go/genai"
	"github.com/iuriikogan/multi-agent-cra/pkg/agent"
	"github.com/iuriikogan/multi-agent-cra/pkg/config"
	"github.com/iuriikogan/multi-agent-cra/pkg/core"
	"github.com/iuriikogan/multi-agent-cra/pkg/queue"
	"github.com/iuriikogan/multi-agent-cra/pkg/store"
	"github.com/iuriikogan/multi-agent-cra/pkg/tools"
	"github.com/iuriikogan/multi-agent-cra/pkg/workflow"
	"google.golang.org/api/option"
)

// Start initiates the worker process
func Start(ctx context.Context, cfg *config.Config, pubsubClient *queue.Client, db store.Store) error {
	genaiClient, err := genai.NewClient(ctx, option.WithAPIKey(cfg.APIKey))
	if err != nil {
		return fmt.Errorf("failed to create GenAI client: %w", err)
	}
	defer genaiClient.Close()

	aggregatorAgent := agent.New(genaiClient, cfg.APIKey, "ResourceAggregator", "Ingestion", "gemini-3.1-flash-lite-preview",
		agent.WithSystemInstruction(`You are an expert Google Cloud Resource Aggregator.
Your primary responsibility is to efficiently discover, list, and ingest all relevant GCP assets within the specified scope.
When requested, you must utilize the list_gcp_assets tool to fetch this data.
CRITICAL CONSTRAINT: You must return the results strictly as a raw JSON array of asset objects. Do not include any markdown formatting, conversational text, explanations, or code block backticks. The output must be immediately parsable by json.Unmarshal.`),
		agent.WithTools(tools.IngestionTools...),
	)

	modelerAgent := agent.New(genaiClient, cfg.APIKey, "CRAModeler", "Modeling", "gemini-3-pro-preview",
		agent.WithSystemInstruction(`You are a specialized Cyber Resilience Act (CRA) Modeler.
Your core task is to analyze discovered Google Cloud resources and map them into a structured CRA threat model.
Apply your deep knowledge of cloud architecture and the European CRA framework to identify potential vulnerabilities, establish trust boundaries, and highlight critical components in the resource topology.
Produce a comprehensive, structured modeling report detailing the security posture and architectural risks.`),
	)
	validatorAgent := agent.New(genaiClient, cfg.APIKey, "ComplianceValidator", "Validation", "gemini-3-pro-preview",
		agent.WithSystemInstruction(`You are a strict and meticulous Compliance Validator focused on the European Cyber Resilience Act (CRA).
Your responsibility is to rigorously validate the provided CRA model and resource configurations against all relevant regulatory frameworks and security best practices.
Utilize the regulatory checker and compliance tools to verify configurations.
Your output must be a detailed compliance report that explicitly highlights severe compliance violations, exposes missing security controls, and provides clear, actionable step-by-step remediation plans.`),
		agent.WithTools(tools.RegulatoryCheckerTools...),
		agent.WithTools(tools.ComplianceTools...),
	)
	reviewerAgent := agent.New(genaiClient, cfg.APIKey, "Reviewer", "Approval", "gemini-3-pro-preview",
		agent.WithSystemInstruction(`You are the authoritative Compliance Reviewer acting as the final human-in-the-loop proxy for CRA compliance.
Your job is to critically evaluate the compliance reports and validation findings generated by the system.
You must:
1. Carefully verify the severity and validity of all findings.
2. Assess the feasibility and correctness of proposed remediations.
3. Issue a structured final verdict (e.g., APPROVED, REJECTED, APPROVED_WITH_CONDITIONS).
Justify your verdict based on the overall security posture and strict adherence to the CRA framework.`),
		agent.WithTools(tools.ComplianceTools...),
	)
	taggerAgent := agent.New(genaiClient, cfg.APIKey, "ResourceTagger", "Tagging", "gemini-3.1-flash-lite-preview",
		agent.WithSystemInstruction(`You are an automated Google Cloud Resource Tagger.
Based on the finalized compliance review and identified asset issues, your task is to apply the appropriate GCP tags to resources to effectively track their CRA compliance status and remediation needs.
Use the provided TaggingTools precisely. Do not produce conversational text; only execute the necessary tool calls.
If you apply tags, you must unconditionally end your response with a line exactly matching this format: 'APPLIED_TAGS:' followed by the tags in key=value format (comma-separated).
Example: APPLIED_TAGS: cra_status=non_compliant,remediation=urgent`),
		agent.WithTools(tools.TaggingTools...),
	)

	defer func() {
		_ = aggregatorAgent.Close()
		_ = modelerAgent.Close()
		_ = validatorAgent.Close()
		_ = reviewerAgent.Close()
		_ = taggerAgent.Close()
	}()

	wf := workflow.NewPubSubWorkflow(pubsubClient, db, cfg.PubSub.TopicMonitoring)

	go func() {
		_ = wf.StartStage(ctx, cfg.PubSub.SubAggregator, cfg.PubSub.TopicModeler, aggregatorAgent, workflow.ProcessAggregation)
	}()
	go func() {
		_ = wf.StartStage(ctx, cfg.PubSub.SubModeler, cfg.PubSub.TopicValidator, modelerAgent, workflow.ProcessModeling)
	}()
	go func() {
		_ = wf.StartStage(ctx, cfg.PubSub.SubValidator, cfg.PubSub.TopicReviewer, validatorAgent, workflow.ProcessValidation)
	}()
	go func() {
		_ = wf.StartStage(ctx, cfg.PubSub.SubReviewer, cfg.PubSub.TopicTagger, reviewerAgent, workflow.ProcessReview)
	}()
	go func() {
		_ = wf.StartStage(ctx, cfg.PubSub.SubTagger, "", taggerAgent, workflow.ProcessTagging)
	}()

	slog.Info("Worker started: Listening for scan requests...")
	err = pubsubClient.Subscribe(ctx, cfg.PubSub.SubScanRequests, func(ctx context.Context, data []byte) error {
		var job struct {
			JobID string `json:"job_id"`
			Scope string `json:"scope"`
		}
		if err := json.Unmarshal(data, &job); err != nil {
			return fmt.Errorf("failed to parse job: %w", err)
		}

		slog.Info("Processing scan request", "job_id", job.JobID)

		if db != nil {
			if err := db.CreateScan(ctx, job.JobID, job.Scope); err != nil {
				slog.Error("Failed to create scan record", "error", err)
				return err
			}
		}

		err := runScan(ctx, cfg, pubsubClient, aggregatorAgent, job.Scope, job.JobID, db)

		status := "completed"
		if err != nil {
			slog.Error("Scan failed", "error", err)
			status = "failed"
		}

		if db != nil {
			if err := db.UpdateScanStatus(ctx, job.JobID, status); err != nil {
				slog.Error("Failed to update status", "error", err)
			}
		}
		return nil
	})
	if err != nil && ctx.Err() == nil {
		return fmt.Errorf("subscription error: %w", err)
	}
	slog.Info("Worker stopped")
	return nil
}

func runScan(ctx context.Context, cfg *config.Config, pubsubClient *queue.Client, aggregator agent.Agent, scope, jobID string, db store.Store) error {
	discoveryCtx, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()

	listResp, err := aggregator.Chat(discoveryCtx, fmt.Sprintf("List all GCP assets in %s", scope))
	if err != nil {
		return err
	}

	jsonStr := listResp
	if start := strings.IndexAny(jsonStr, "[{"); start != -1 {
		if end := strings.LastIndexAny(jsonStr, "}]"); end != -1 && end > start {
			jsonStr = jsonStr[start : end+1]
		}
	}
	jsonStr = strings.TrimSpace(jsonStr)

	type Asset struct {
		Name      string `json:"name"`
		AssetType string `json:"asset_type"`
		Location  string `json:"location"`
	}
	var assets []Asset
	if err := json.Unmarshal([]byte(jsonStr), &assets); err != nil {
		return fmt.Errorf("failed to parse assets: %w", err)
	}

	for i, a := range assets {
		task := workflow.AgentTask{
			JobID: jobID,
			Scope: scope,
			Resource: core.GCPResource{
				ID: fmt.Sprintf("r%d", i), Name: a.Name, Type: a.AssetType, Region: a.Location, ProjectID: scope,
			},
		}
		taskData, _ := json.Marshal(task)
		if err := pubsubClient.Publish(ctx, cfg.PubSub.TopicAggregator, taskData); err != nil {
			slog.Error("Failed to publish aggregator task", "error", err)
		}
	}
	return nil
}
