// Package worker implements the core processing logic for assessment agents.
package worker

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strings"
	"time"

	"github.com/google/generative-ai-go/genai"
	"github.com/iuriikogan/multi-agent-cra/pkg/agent"
	"github.com/iuriikogan/multi-agent-cra/pkg/config"
	"github.com/iuriikogan/multi-agent-cra/pkg/core"
	"github.com/iuriikogan/multi-agent-cra/pkg/queue"
	"github.com/iuriikogan/multi-agent-cra/pkg/store"
	"github.com/iuriikogan/multi-agent-cra/pkg/tools"
	"github.com/iuriikogan/multi-agent-cra/pkg/workflow"
	"google.golang.org/api/option"
)

// RegisterRoutes configures HTTP and Pub/Sub handlers for worker agents.
// It returns a cleanup function to release agent resources and an error if initialization fails.
func RegisterRoutes(ctx context.Context, mux *http.ServeMux, cfg *config.Config, pubsubClient *queue.Client, db store.Store) (func(), error) {
	genaiClient, err := genai.NewClient(ctx, option.WithAPIKey(cfg.APIKey))
	if err != nil {
		return nil, fmt.Errorf("failed to create GenAI client: %w", err)
	}

	aggregatorAgent := agent.New(genaiClient, cfg.APIKey, "ResourceAggregator", "Ingestion", cfg.Models.Aggregator,
		agent.WithSystemInstruction(`You are an expert Google Cloud Resource Aggregator.
Your primary responsibility is to efficiently discover, list, and ingest all relevant GCP assets within the specified scope.
When requested, you must utilize the list_gcp_assets tool to fetch this data.
CRITICAL CONSTRAINT: You must return the results strictly as a raw JSON array of asset objects. Do not include any markdown formatting, conversational text, explanations, or code block backticks. The output must be immediately parsable by json.Unmarshal.`),
		agent.WithTools(tools.IngestionTools...),
	)

	modelerAgent := agent.New(genaiClient, cfg.APIKey, "CRAModeler", "Modeling", cfg.Models.Modeler,
		agent.WithSystemInstruction(`You are a specialized Cyber Resilience Act (CRA) Modeler.
Your core task is to analyze discovered Google Cloud resources and map them into a structured CRA threat model.
Apply your deep knowledge of cloud architecture and the European CRA framework to identify potential vulnerabilities, establish trust boundaries, and highlight critical components in the resource topology.
Produce a comprehensive, structured modeling report detailing the security posture and architectural risks.`),
	)
	validatorAgent := agent.New(genaiClient, cfg.APIKey, "ComplianceValidator", "Validation", cfg.Models.Validator,
		agent.WithSystemInstruction(`You are a strict and meticulous Compliance Validator focused on the European Cyber Resilience Act (CRA).
Your responsibility is to rigorously validate the provided CRA model and resource configurations against all relevant regulatory frameworks and security best practices.
Utilize the regulatory checker and compliance tools to verify configurations.
Your output must be a detailed compliance report that explicitly highlights severe compliance violations, exposes missing security controls, and provides clear, actionable step-by-step remediation plans.`),
		agent.WithTools(tools.RegulatoryCheckerTools...),
		agent.WithTools(tools.ComplianceTools...),
	)
	reviewerAgent := agent.New(genaiClient, cfg.APIKey, "Reviewer", "Approval", cfg.Models.Reviewer,
		agent.WithSystemInstruction(`You are the authoritative Compliance Reviewer acting as the final human-in-the-loop proxy for CRA compliance.
Your job is to critically evaluate the compliance reports and validation findings generated by the system.
You must:
1. Carefully verify the severity and validity of all findings.
2. Assess the feasibility and correctness of proposed remediations.
3. Issue a structured final verdict (e.g., APPROVED, REJECTED, APPROVED_WITH_CONDITIONS).
Justify your verdict based on the overall security posture and strict adherence to the CRA framework.`),
		agent.WithTools(tools.ComplianceTools...),
	)
	taggerAgent := agent.New(genaiClient, cfg.APIKey, "ResourceTagger", "Tagging", cfg.Models.Tagger,
		agent.WithSystemInstruction(`You are an automated Google Cloud Resource Tagger.
Based on the finalized compliance review and identified asset issues, your task is to apply the appropriate GCP tags to resources to effectively track their CRA compliance status and remediation needs.
Use the provided TaggingTools precisely. Do not produce conversational text; only execute the necessary tool calls.
If you apply tags, you must unconditionally end your response with a line exactly matching this format: 'APPLIED_TAGS:' followed by the tags in key=value format (comma-separated).
Example: APPLIED_TAGS: cra_status=non_compliant,remediation=urgent`),
		agent.WithTools(tools.TaggingTools...),
	)

	reporterAgent := agent.New(genaiClient, cfg.APIKey, "Reporter", "Reporting", cfg.Models.Reporter,
		agent.WithSystemInstruction(`You are a CRA Compliance Reporter.
Your task is to generate a final report for the CRA scan.
The report should include the resource name, the compliance status, and a detailed explanation of the finding.
The output should be a JSON object with the following fields: 'resource_name', 'status', 'details'.`),
	)

	cleanup := func() {
		_ = aggregatorAgent.Close()
		_ = modelerAgent.Close()
		_ = validatorAgent.Close()
		_ = reviewerAgent.Close()
		_ = taggerAgent.Close()
		_ = reporterAgent.Close()
		_ = genaiClient.Close()
	}

	wf := workflow.NewPubSubWorkflow(pubsubClient, db, cfg.PubSub.TopicMonitoring)

	wf.RegisterPushHandler(mux, "/pubsub/aggregator", cfg.PubSub.TopicModeler, aggregatorAgent, workflow.ProcessAggregation)
	wf.RegisterPushHandler(mux, "/pubsub/modeler", cfg.PubSub.TopicValidator, modelerAgent, workflow.ProcessModeling)
	wf.RegisterPushHandler(mux, "/pubsub/validator", cfg.PubSub.TopicReviewer, validatorAgent, workflow.ProcessValidation)
	wf.RegisterPushHandler(mux, "/pubsub/reviewer", cfg.PubSub.TopicTagger, reviewerAgent, workflow.ProcessReview)
	wf.RegisterPushHandler(mux, "/pubsub/tagger", cfg.PubSub.TopicReporter, taggerAgent, workflow.ProcessTagging)
	wf.RegisterPushHandler(mux, "/pubsub/reporter", "", reporterAgent, workflow.ProcessReporting)

	slog.Info("Worker routes registered. Listening for push requests...")
	
	mux.HandleFunc("/pubsub/scan-requests", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
			return
		}

		var req workflow.PushMessage
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, "bad request", http.StatusBadRequest)
			return
		}

		var job struct {
			JobID string `json:"job_id"`
			Scope string `json:"scope"`
		}
		if err := json.Unmarshal(req.Message.Data, &job); err != nil {
			slog.Error("Failed to parse job from push", "error", err)
			w.WriteHeader(http.StatusOK)
			return
		}

		slog.Info("Processing scan request", "job_id", job.JobID)

		if db != nil {
			if err := db.CreateScan(r.Context(), job.JobID, job.Scope); err != nil {
				slog.Error("Failed to create scan record", "error", err)
				http.Error(w, "db error", http.StatusInternalServerError)
				return
			}
		}

		err := runScan(r.Context(), cfg, pubsubClient, aggregatorAgent, job.Scope, job.JobID, db)

		status := "completed"
		if err != nil {
			slog.Error("Scan failed", "error", err)
			status = "failed"
		}

		if db != nil {
			if err := db.UpdateScanStatus(r.Context(), job.JobID, status); err != nil {
				slog.Error("Failed to update status", "error", err)
			}
		}

		if err != nil {
			http.Error(w, "scan failed", http.StatusInternalServerError)
			return
		}

		w.WriteHeader(http.StatusOK)
	})

	return cleanup, nil
}

// runScan executes resource discovery and delegates assessment tasks to agents.
func runScan(ctx context.Context, cfg *config.Config, pubsubClient *queue.Client, aggregator agent.Agent, scope, jobID string, db store.Store) error {
	discoveryCtx, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()

	listResp, err := aggregator.Chat(discoveryCtx, fmt.Sprintf("List all GCP assets in %s", scope))
	if err != nil {
		return err
	}

	jsonStr := listResp
	
	type Asset struct {
		Name      string `json:"name"`
		AssetType string `json:"asset_type"`
		Location  string `json:"location"`
	}
	var assets []Asset

	parsed := false
	if start := strings.Index(jsonStr, "["); start != -1 {
		if end := strings.LastIndex(jsonStr, "]"); end != -1 && end > start {
			arrayStr := jsonStr[start : end+1]
			if err := json.Unmarshal([]byte(arrayStr), &assets); err == nil {
				parsed = true
			}
		}
	}

	if !parsed {
		jsonStr = strings.TrimSpace(jsonStr)
		if err := json.Unmarshal([]byte(jsonStr), &assets); err != nil {
			var singleAsset Asset
			if err2 := json.Unmarshal([]byte(jsonStr), &singleAsset); err2 == nil {
				assets = []Asset{singleAsset}
			} else {
				var wrapper struct {
					Assets []Asset `json:"assets"`
				}
				if err3 := json.Unmarshal([]byte(jsonStr), &wrapper); err3 == nil && wrapper.Assets != nil {
					assets = wrapper.Assets
				} else {
					return fmt.Errorf("failed to parse assets: %w", err)
				}
			}
		}
	}

	for i, a := range assets {
		task := workflow.AgentTask{
			JobID: jobID,
			Scope: scope,
			Resource: core.GCPResource{
				ID: fmt.Sprintf("r%d", i), Name: a.Name, Type: a.AssetType, Region: a.Location, ProjectID: scope,
			},
		}
		taskData, _ := json.Marshal(task)
		if err := pubsubClient.Publish(ctx, cfg.PubSub.TopicAggregator, taskData); err != nil {
			slog.Error("Failed to publish aggregator task", "error", err)
		}
	}
	return nil
}
